github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.JAVA_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-buildpacks"

package:
  repository:     gcr.io/paketo-buildpacks/maven
  register:       true
  registry_token: ${{ secrets.JAVA_GITHUB_TOKEN }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.JAVA_GCLOUD_SERVICE_ACCOUNT_KEY }}

dependencies:
- name:            Maven 3
  id:              maven
  uses:            docker://ghcr.io/paketo-buildpacks/actions/maven-dependency:main
  version_pattern: "^3\\.[\\d]+\\.[\\d]+"
  with:
    uri:           https://repo1.maven.org/maven2
    group_id:      org.apache.maven
    artifact_id:   apache-maven
    classifier:    bin
    packaging:     tar.gz
    version_regex: ^3\\.[\\d]+\\.[\\d]+$
- name:            Maven 4
  id:              maven
  uses:            docker://ghcr.io/paketo-buildpacks/actions/maven-dependency:main
  version_pattern: "^4\\.[\\d]+\\.[\\d]+"
  with:
    uri:           https://repo1.maven.org/maven2
    group_id:      org.apache.maven
    artifact_id:   apache-maven
    classifier:    bin
    packaging:     tar.gz
    version_regex: ^4\\.[\\d]+\\.[\\d]+-.*$
- id:   mvnd
  uses: docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    owner: apache
    repository: maven-mvnd
    glob: mvnd-.+-linux-amd64.zip
    token: ${{ secrets.JAVA_GITHUB_TOKEN }}
